version: '3'

services:
  co-creation:
    image: co-creation:latest
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '1.0'  # Adjust the CPU limit as needed
          memory: 512M  # Adjust the memory limit as needed
          reservations:
            devices:
              - driver: nvidia
                capabilities: [gpu]
                count: all
    restart: unless-stopped
