apiVersion: v1
kind: Service
metadata:
  name: cocreation-svc
  namespace: zingcam
  annotations:
    cloud.google.com/backend-config: '{"default": "cocreation-be-config"}'
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    app: cocreation
  type: NodePort
