apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: cocreation-be-config
  namespace: zingcam
spec:
  timeoutSec: 600
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /cocreation/health
    port: 8000
